server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sale_mate_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
logging:
  level:
    root: debug

wx:
  suiteId: wwd8f33f6b35076520
  suiteSecret: _wCwFuRPwrR3AbV7m1iDxBThM11LI341bmDRQrKGa3Q
  upload: /Users/song/Downloads/usr/local/upload
  # 信任域名
  trustHostList:
    - http://salemate.pinbar.vip/
  callDataToken: murI0
  callDataEncodingAESKey: M6Xe6BQV3nthE91ohO2EaFPr6q8RNxXye36arhDVQZE
# 登录回调令牌
  loginToken: mmnkv3fSPIPyIr5j1slxIvg
  loginEncodingAESKey: 6v0KlKwFtLtr2P4OaQmVZpzMfkpFw944wpkYOVUf39k
  loginSuiteID: ww67ff055de7bf9ee4
  loginSecret: t966QBbPkABY0NejK61GXdYEgL6mIb-sWOnmRYWf_Z8
